### ISSUE TITLE
Okex broken

### ISSUE THREAD

**Issue by armyanov** [Tucsky/SignificantTrades#16]
Hi!

All my instances stopped working today, seems that the culprit is Okex. 

SyntaxError: Unexpected token M in JSON at position 0
    at JSON.parse (<anonymous>)
    at Okex.format (/home/user/SignificantTrades/server/src/exchanges/okex.js:567:23)
    at WebSocket.api.on.event (/home/user/SignificantTrades/server/src/exchanges/okex.js:530:56)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at Receiver.receiverOnMessage (/home/user/SignificantTrades/server/node_modules/ws/lib/websocket.js:741:20)
    at emitOne (events.js:116:13)
    at Receiver.emit (events.js:211:7)
    at Receiver.dataMessage (/home/user/SignificantTrades/server/node_modules/ws/lib/receiver.js:405:14)
    at Receiver.getData (/home/user/SignificantTrades/server/node_modules/ws/lib/receiver.js:346:17)

I am a "bit" of a noob so a little help would be appreciated.

Thanks!

**Comment by Piterden** [comment]
Are you sure it is json?

**Comment by Tucsky** [comment]
It seems that OKEX just forced compression on their messages https://github.com/okcoin-okex/API-docs-OKEx.com/commit/eee5b2ac806af7acca3f5e21a5b4ba5ebf7f2d98
I think it was only when putting ?compress=true on the websocket until today
> Our system will eventually ignore the "compress" parameter and return the compressed message directly.

I pushed a fix on the feature/server branch this morning based on their demo (2 weeks old https://github.com/okcoin-okex/API-docs-OKEx.com/tree/master/demo#nodejs) 

https://github.com/Tucsky/SignificantTrades/blob/7dab7c60dcd984b7cc91aa90d1ccf9f4b071a88e/src/exchanges/okex.js#L569

```
    let json;
    
    try {
      if (event instanceof String) {
        json = JSON.parse(event);
      } else {
        json = JSON.parse(pako.inflateRaw(event, {to: 'string'}));
      }
    } catch (error) {
      console.error(`[okex] failed to parse event data`, error);
      return;
    }
```

I was not aware of that at all.
